export enum AuctionEventType {
  AUCTION_CREATED = 'AUCTION_CREATED',
  AUCTION_CANCELLED = 'AUCTION_CANCELLED',
  BID_PLACED = 'BID_PLACED',
  FUNDS_CLAIMED = 'FUNDS_CLAIMED',
  ITEM_CLAIMED = 'ITEM_CLAIMED',
}
